// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABFFvmIkQSJVJfZXjY_okAgw3udYJugpk',
    appId: '1:872161769698:web:8048482123c1c51c4f86bb',
    messagingSenderId: '872161769698',
    projectId: 'smart-assistant-gudang-iii',
    authDomain: 'smart-assistant-gudang-iii.firebaseapp.com',
    databaseURL: 'https://smart-assistant-gudang-iii-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-assistant-gudang-iii.firebasestorage.app',
    measurementId: 'G-JM2E7FTGF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyQxWtqb_9lsILnhUDKuHBsO-ULqvVeCs',
    appId: '1:872161769698:android:36833be944c008604f86bb',
    messagingSenderId: '872161769698',
    projectId: 'smart-assistant-gudang-iii',
    databaseURL: 'https://smart-assistant-gudang-iii-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-assistant-gudang-iii.firebasestorage.app',
  );
}
